package com.lockOnActive

import com.tewinsid.drools.model.Person

rule "lock-on-active-test-1"

    when
        $p : Person(age < 20)
    then
        System.out.println("lock-on-active-test-1 触发 age= " + $p.getAge());
        $p.setAge(21);
        update($p)
    end
rule "lock-on-active-test-2"
    lock-on-active true
    when
        $p : Person(age >= 20)
    then
        System.out.println("lock-on-active-test-2 触发 age= " + $p.getAge());
    end